public class Fibonacci {
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
	 

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int first = 1;
		int second = 2;
		int run = 1;
		long sum = 2;
		while (run == 1) {
			int count = first + second;
			System.out.println(count);
			first = second;
			second = count;
			if (count > 4000000) run =0;
			else  			if (count %2 == 0) sum = sum + count;
			System.out.println("sum = " +sum);


		}
		System.out.println("sum = " +sum);

	}

}
